import React, { useState, useEffect, useRef } from "react";
import { parseBook } from "../utils/ebookParser";
import ReaderControls from "../components/ReaderControls";
import ReaderSidePanel from "../components/ReaderSidePanel";
import { List } from "lucide-react";
import {
  Bookmark,
  NotebookPen,
  Users,
  ChevronLeft,
  ChevronRight,
  BookOpen,
  X,
} from "lucide-react";
import ReaderContent from "../components/ReaderContent";
import ChapterSidebar from "../components/ChapterSidebar";
import ReaderContentSkeleton from "../components/ReaderContentSkeleton";
import { useReaderTheme } from "../context/ReaderThemeContext";

const CHARS_PER_PAGE = 8000; // Increased characters per page to fill the screen
function paginateText(text, charsPerPage = 5000) {
  if (!text) return [""];

  const pages = [];
  let start = 0;

  while (start < text.length) {
    let end = start + charsPerPage;

    if (end < text.length) {
      while (end > start && text[end] !== " ") {
        end--;
      }
    }

    pages.push(text.slice(start, end));
    start = end;
  }

  return pages;
}

/**
 * EbookReader – renders a book as paginated black‑on‑white pages.
 * It also supports collaborative reading rooms where participants can
 * see each other's presence (name + current page) and invite others via a token.
 *
 * Props:
 *   book   – book object containing at least `title`, `author`, `ebook_text`.
 *   client – API client generated by useClient (used for all backend calls).
 *   onBack – callback invoked when the user clicks the back button.
 */
export function EbookReader({ book, client, onBack }) {
  // ---- Core reading state -------------------------------------------------
  const [pages, setPages] = useState([]);
  const [pageIndex, setPageIndex] = useState(0);
  const pageRef = useRef(null);
  const measureRef = useRef(null);
  // ---- Collaborative room state -------------------------------------------
  const [showPanel, setShowPanel] = useState("room");
  const [rooms, setRooms] = useState([]);
  const [activeRoom, setActiveRoom] = useState(null);
  const [roomData, setRoomData] = useState(null);
  const [participants, setParticipants] = useState([]);
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteToken, setInviteToken] = useState("");
  const [inviteTokenInput, setInviteTokenInput] = useState("");

  // Notes / bookmarks UI state (unchanged from original implementation)
  const [noteBody, setNoteBody] = useState("");
  const [bookmarkLabel, setBookmarkLabel] = useState("");
  const [msg, setMsg] = useState("");
  // Chapter index for navigation
  const [chapters, setChapters] = useState([]);
  const [showChapters, setShowChapters] = useState(false);
  const [isPaginating, setIsPaginating] = useState(true);

  const ebookText = book?.ebook_text ?? book?.ebook?.text ?? "";

  const [blocks, setBlocks] = useState([]);
  const { theme, warmth, fontFamily, fontSize, lineHeight, layoutMode } = useReaderTheme();

  useEffect(() => {
    if (!book) return;

    const parsed = parseBook(book);

    setBlocks(parsed.blocks);
    setChapters(parsed.chapters);
    setPageIndex(0);
  }, [book]);

  // ---- Keyboard Arrow Navigation ------------------------------------------
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (layoutMode === "scroll") return;

      const activeEl = document.activeElement;
      if (
        activeEl &&
        (activeEl.tagName === "INPUT" ||
          activeEl.tagName === "TEXTAREA" ||
          activeEl.tagName === "SELECT" ||
          activeEl.isContentEditable)
      ) {
        return;
      }

      if (e.key === "ArrowLeft") {
        setPageIndex((p) => Math.max(0, p - 1));
      } else if (e.key === "ArrowRight") {
        setPageIndex((p) => Math.min(pages.length - 1, p + 1));
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [pages.length, layoutMode]);

  // ---- Load available rooms for the user ----------------------------------
  useEffect(() => {
    client
      .request("/rooms")
      .then(setRooms)
      .catch(() => { });
    // If a room was passed via navigation (book._joinRoomId), auto‑join it.
    if (book._joinRoomId) {
      joinRoom(book._joinRoomId);
      setShowPanel("notes");
    }
  }, []);

  // ---- When a room becomes active, fetch its details and start polling -----
  useEffect(() => {
    if (activeRoom) loadRoom();
  }, [activeRoom]);

  // ---- Poll participants every 5 seconds ----------------------------------
  useEffect(() => {
    if (!activeRoom) return undefined;
    const poll = async () => {
      try {
        const data = await client.request(`/rooms/${activeRoom}/presence`);
        setParticipants(data.participants || []);
      } catch (_) { }
    };
    poll(); // initial fetch
    const interval = setInterval(poll, 5000);
    return () => clearInterval(interval);
  }, [activeRoom]);

  // ---- Whenever the local page changes, push presence update --------------
  useEffect(() => {
    if (!activeRoom) return;
    client
      .request(`/rooms/${activeRoom}/presence`, {
        method: "POST",
        body: JSON.stringify({ page_index: pageIndex }),
      })
      .catch(() => { });
  }, [pageIndex, activeRoom]);

  // -----------------------------------------------------------------------
  function fitsOnPage(candidateBlocks) {
    if (!measureRef.current || !pageRef.current) return true;

    const measure = measureRef.current;

    measure.innerHTML = "";

    candidateBlocks.forEach((block) => {
      const el = document.createElement(block.type === "heading" ? "h2" : "p");

      el.textContent = block.text;

      if (block.type === "heading") {
        el.style.cssText = `
        text-align: center;
        font-size: ${Math.round(fontSize * 1.5)}px;
        font-weight: 700;
        margin: 32px 0 24px;
        letter-spacing: .03em;
        font-family: ${fontFamily};
      `;
      } else {
        el.style.cssText = `
        font-size: ${fontSize}px;
        line-height: ${lineHeight};
        margin: 0 0 18px;
        text-align: justify;
        text-indent: 2em;
        font-family: ${fontFamily};
      `;
      }

      measure.appendChild(el);
    });

    return measure.scrollHeight <= pageRef.current.clientHeight;
  }

  function paginate(blocks) {
    const pages = [];

    const chapters = [];
    let currentPage = [];

    for (const block of blocks) {
      const candidate = [...currentPage, block];

      // Entire block fits
      if (fitsOnPage(candidate)) {

        if (block.type === "heading") {
          chapters.push({
            title: block.text,
            pageIndex: pages.length,
          });
        }

        currentPage = candidate;
        continue;
      }

      // Heading never gets split
      if (block.type === "heading") {

        if (currentPage.length) {
          pages.push({
            lines: currentPage,
          });
        }

        chapters.push({
          title: block.text,
          pageIndex: pages.length,
        });

        currentPage = [block];
        continue;
      }

      // Paragraph doesn't fit.
      // We'll split only the overflowing part.

      if (block.type === "heading") {
        if (currentPage.length) {
          pages.push({ lines: currentPage });
        }

        currentPage = [block];
        continue;
      }

      const words = block.text.split(/\s+/);

      let start = 0;

      while (start < words.length) {
        let low = start;
        let high = words.length;

        let best = start;

        while (low <= high) {
          const mid = Math.floor((low + high) / 2);

          const test = [
            ...currentPage,
            {
              type: "paragraph",
              text: words.slice(start, mid).join(" "),
            },
          ];

          if (fitsOnPage(test)) {
            best = mid;
            low = mid + 1;
          } else {
            high = mid - 1;
          }
        }

        if (best === start) best++;

        currentPage.push({
          type: "paragraph",
          text: words.slice(start, best).join(" "),
        });

        pages.push({
          lines: currentPage,
        });

        currentPage = [];

        start = best;
      }
    }

    if (currentPage.length) {
      pages.push({
        lines: currentPage,
      });
    }
    return {
      pages,
      chapters,
    };
  }

  useEffect(() => {
    if (!blocks.length) return;
    setIsPaginating(true);

    const result = paginate(blocks);

    setPages(result.pages);
    setChapters(result.chapters);

    setIsPaginating(false);
  }, [blocks]);

  useEffect(() => {
    const resize = () => {
      if (!blocks.length) return;

      const result = paginate(blocks);
      setPages(result.pages);
      setChapters(result.chapters);
    };

    window.addEventListener("resize", resize);

    return () => window.removeEventListener("resize", resize);
  }, [blocks]);

  useEffect(() => {
    if (!pageRef.current || !measureRef.current) return;

    measureRef.current.style.width = `${pageRef.current.clientWidth}px`;
  }, [pages]);

  async function loadRoom() {
    try {
      const data = await client.request(`/rooms/${activeRoom}`);
      setRoomData(data);
    } catch (e) {
      setMsg(e.message);
    }
  }

  const headingRegex =
    /^\s*(?:Chapter|Letter)\s+(\d+|[IVXLCDM]+)\s*$|^\s*[IVXLCDM]+\s*$/i;

  const lines = ebookText.split("\n");

  let firstHeading = null;
  let secondOccurrenceIndex = -1;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (!headingRegex.test(line)) continue;

    if (!firstHeading) {
      firstHeading = line.toLowerCase();
      continue;
    }

    if (line.toLowerCase() === firstHeading) {
      secondOccurrenceIndex = i;
      break;
    }
  }

  const actualBookText =
    secondOccurrenceIndex !== -1
      ? lines.slice(secondOccurrenceIndex).join("\n")
      : ebookText;



  async function createRoom() {
    try {
      const room = await client.request("/rooms", {
        method: "POST",
        body: JSON.stringify({
          book_id: book.id,
          name: `${book.title} reading room`,
        }),
      });
      setActiveRoom(room.id);
      const updated = await client.request("/rooms");
      setRooms(updated);
    } catch (e) {
      setMsg(e.message);
    }
  }

  async function joinRoom(id) {
    try {
      await client.request(`/rooms/${id}/join`, { method: "POST" });
      setActiveRoom(id);
    } catch (e) {
      setMsg(e.message);
    }
  }

  async function addNote(e) {
    e.preventDefault();
    try {
      await client.request(`/rooms/${activeRoom}/notes`, {
        method: "POST",
        body: JSON.stringify({
          location: `Page ${pageIndex + 1}`,
          body: noteBody,
        }),
      });
      setNoteBody("");
      await loadRoom();
    } catch (e) {
      setMsg(e.message);
    }
  }

  async function addBookmark(e) {
    e.preventDefault();
    try {
      await client.request(`/rooms/${activeRoom}/bookmarks`, {
        method: "POST",
        body: JSON.stringify({
          location: `Page ${pageIndex + 1}`,
          label: bookmarkLabel,
        }),
      });
      setBookmarkLabel("");
      await loadRoom();
    } catch (e) {
      setMsg(e.message);
    }
  }

  // Invite creation – returns a token that can be shared with another user.
  async function createInvite() {
    if (!inviteEmail) {
      setMsg("Email is required to create an invite");
      return;
    }
    try {
      const data = await client.request(`/rooms/${activeRoom}/invite`, {
        method: "POST",
        body: JSON.stringify({ email: inviteEmail }),
      });
      setInviteToken(data.invite_token);
      setMsg("Invite token generated – share it with the other reader");
    } catch (e) {
      setMsg(e.message);
    }
  }

  // Accept an invitation token received from another user.
  async function acceptInvite() {
    if (!inviteTokenInput) {
      setMsg("Invite token is required");
      return;
    }
    try {
      const resp = await client.request(`/rooms/invite/accept`, {
        method: "POST",
        body: JSON.stringify({ token: inviteTokenInput }),
      });
      // The server returns the room_id; we can set it as active.
      setActiveRoom(resp.room_id);
      setInviteTokenInput("");
      setMsg("Joined room via invite token");
    } catch (e) {
      setMsg(e.message);
    }
  }

  const bookRooms = rooms.filter(
    (r) => r.book_id === book.id || r.title === book.title,
  );
  const currentPage = pages[pageIndex] ?? { lines: [] };
  const totalPages = pages.length;
  return (
    <div className={`relative w-full bg-white dark:bg-zinc-955 text-zinc-900 dark:text-zinc-100 transition-colors duration-200 ${layoutMode === "scroll" ? "min-h-screen h-auto overflow-y-visible" : "h-screen overflow-hidden"
      }`}>
      {/* Warmth overlay shade */}
      <div
        className="warmth-overlay fixed inset-0 pointer-events-none z-20 transition-opacity duration-200"
        style={{ opacity: warmth / 100 }}
      />

      <div className="flex h-full w-full relative">
        {/* Main reader area */}
        <div className="flex-1 flex justify-center items-center relative h-full">
          <ReaderContent
            ref={pageRef}
            currentPage={currentPage}
            pages={pages}
            pageIndex={pageIndex}
            totalPages={totalPages}
            onPrevious={() => setPageIndex((p) => Math.max(0, p - 1))}
            onNext={() => setPageIndex((p) => Math.min(totalPages - 1, p + 1))}
            style={{
              visibility: isPaginating ? "hidden" : "visible",
            }}
          />
          {isPaginating && (
            <div className="absolute inset-0 z-10 flex items-center justify-center bg-white dark:bg-zinc-950">
              <ReaderContentSkeleton />
            </div>
          )}
          <div
            ref={measureRef}
            style={{
              position: "fixed",
              left: "-9999px",
              top: 0,
              visibility: "hidden",
              width: pageRef.current?.clientWidth || 900,
              height: "auto",
              padding: "40px 55px",
              boxSizing: "border-box",
              fontFamily: fontFamily,
              fontSize: `${fontSize}px`,
              lineHeight: lineHeight,
            }}
          />
        </div>
      </div>

      <ChapterSidebar
        open={showChapters}
        chapters={chapters}
        bookmarks={[]}
        pageIndex={pageIndex}
        onClose={() => setShowChapters(false)}
        onSelectChapter={(page) => {
          if (layoutMode === "scroll") {
            let blockIndex = 0;
            for (let i = 0; i < page; i++) {
              blockIndex += pages[i]?.lines?.length || 0;
            }
            const el = document.getElementById(`block-${blockIndex}`);
            if (el) {
              el.scrollIntoView({ behavior: "smooth" });
            }
          } else {
            setPageIndex(page);
          }
          setShowChapters(false);
        }}
      />

      <ReaderControls
        pageIndex={pageIndex}
        totalPages={totalPages}
        onPrevious={() => setPageIndex((p) => Math.max(0, p - 1))}
        onNext={() => setPageIndex((p) => Math.min(totalPages - 1, p + 1))}
        onOpenChapters={() => setShowChapters(true)}
        onBack={onBack}
      />
    </div>
  );
}