import ChapterSidebar from "../components/ChapterSidebar";
import React, { useState, useEffect, useRef } from "react";
import { parseBook } from "../utils/ebookParser";
import {
  Bookmark,
  NotebookPen,
  Users,
  ChevronLeft,
  ChevronRight,
  BookOpen,
  X,
} from "lucide-react";

const CHARS_PER_PAGE = 8000; // Increased characters per page to fill the screen
function paginateText(text, charsPerPage = 5000) {
  if (!text) return [""];

  const pages = [];
  let start = 0;

  while (start < text.length) {
    let end = start + charsPerPage;

    if (end < text.length) {
      while (end > start && text[end] !== " ") {
        end--;
      }
    }

    pages.push(text.slice(start, end));
    start = end;
  }

  return pages;
}

/**
 * EbookReader – renders a book as paginated black‑on‑white pages.
 * It also supports collaborative reading rooms where participants can
 * see each other's presence (name + current page) and invite others via a token.
 *
 * Props:
 *   book   – book object containing at least `title`, `author`, `ebook_text`.
 *   client – API client generated by useClient (used for all backend calls).
 *   onBack – callback invoked when the user clicks the back button.
 */
export function EbookReader({ book, client }) {
  // Add a container class for centering and monochrome styling

  // ---- Core reading state -------------------------------------------------
  const [pages, setPages] = useState([]);
  const [pageIndex, setPageIndex] = useState(0);
  const textRef = useRef(null);

  // ---- Collaborative room state -------------------------------------------
  const [showPanel, setShowPanel] = useState(null); // "notes" | "bookmarks" | "room"
  const [rooms, setRooms] = useState([]);
  const [activeRoom, setActiveRoom] = useState(null);
  const [roomData, setRoomData] = useState(null);
  const [participants, setParticipants] = useState([]);
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteToken, setInviteToken] = useState("");
  const [inviteTokenInput, setInviteTokenInput] = useState("");

  // Notes / bookmarks UI state (unchanged from original implementation)
  const [noteBody, setNoteBody] = useState("");
  const [bookmarkLabel, setBookmarkLabel] = useState("");
  const [msg, setMsg] = useState("");
  // Chapter index for navigation
  const [chapters, setChapters] = useState([]);
  const [showChapters, setShowChapters] = useState(false);
  
   const ebookText = book?.ebook_text ?? book?.ebook?.text ?? "";

  // ---- Load book text into pages ------------------------------------------
  useEffect(() => {
  const { pages, chapters } = parseBook(book);

  setPages(pages);
  setChapters(chapters);
  setPageIndex(0);
}, [book]);

  // ---- Load available rooms for the user ----------------------------------
  useEffect(() => {
    client
      .request("/rooms")
      .then(setRooms)
      .catch(() => {});
    // If a room was passed via navigation (book._joinRoomId), auto‑join it.
    if (book._joinRoomId) {
      joinRoom(book._joinRoomId);
      setShowPanel("notes");
    }
  }, []);

  // ---- When a room becomes active, fetch its details and start polling -----
  useEffect(() => {
    if (activeRoom) loadRoom();
  }, [activeRoom]);

  // ---- Poll participants every 5 seconds ----------------------------------
  useEffect(() => {
    if (!activeRoom) return undefined;
    const poll = async () => {
      try {
        const data = await client.request(`/rooms/${activeRoom}/presence`);
        setParticipants(data.participants || []);
      } catch (_) {}
    };
    poll(); // initial fetch
    const interval = setInterval(poll, 5000);
    return () => clearInterval(interval);
  }, [activeRoom]);

  // ---- Whenever the local page changes, push presence update --------------
  useEffect(() => {
    if (!activeRoom) return;
    client
      .request(`/rooms/${activeRoom}/presence`, {
        method: "POST",
        body: JSON.stringify({ page_index: pageIndex }),
      })
      .catch(() => {});
  }, [pageIndex, activeRoom]);

  // -----------------------------------------------------------------------
  async function loadRoom() {
    try {
      const data = await client.request(`/rooms/${activeRoom}`);
      setRoomData(data);
    } catch (e) {
      setMsg(e.message);
    }
  }

const headingRegex =
  /^\s*(?:Chapter|Letter)\s+(\d+|[IVXLCDM]+)\s*$|^\s*[IVXLCDM]+\s*$/i;

const lines = ebookText.split("\n");

let firstHeading = null;
let secondOccurrenceIndex = -1;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i].trim();

  if (!headingRegex.test(line)) continue;

  if (!firstHeading) {
    firstHeading = line.toLowerCase();
    continue;
  }

  if (line.toLowerCase() === firstHeading) {
    secondOccurrenceIndex = i;
    break;
  }
}

const actualBookText =
  secondOccurrenceIndex !== -1
    ? lines.slice(secondOccurrenceIndex).join("\n")
    : ebookText;



  async function createRoom() {
    try {
      const room = await client.request("/rooms", {
        method: "POST",
        body: JSON.stringify({
          book_id: book.id,
          name: `${book.title} reading room`,
        }),
      });
      setActiveRoom(room.id);
      const updated = await client.request("/rooms");
      setRooms(updated);
    } catch (e) {
      setMsg(e.message);
    }
  }

  async function joinRoom(id) {
    try {
      await client.request(`/rooms/${id}/join`, { method: "POST" });
      setActiveRoom(id);
    } catch (e) {
      setMsg(e.message);
    }
  }

  async function addNote(e) {
    e.preventDefault();
    try {
      await client.request(`/rooms/${activeRoom}/notes`, {
        method: "POST",
        body: JSON.stringify({
          location: `Page ${pageIndex + 1}`,
          body: noteBody,
        }),
      });
      setNoteBody("");
      await loadRoom();
    } catch (e) {
      setMsg(e.message);
    }
  }

  async function addBookmark(e) {
    e.preventDefault();
    try {
      await client.request(`/rooms/${activeRoom}/bookmarks`, {
        method: "POST",
        body: JSON.stringify({
          location: `Page ${pageIndex + 1}`,
          label: bookmarkLabel,
        }),
      });
      setBookmarkLabel("");
      await loadRoom();
    } catch (e) {
      setMsg(e.message);
    }
  }

  // Invite creation – returns a token that can be shared with another user.
  async function createInvite() {
    if (!inviteEmail) {
      setMsg("Email is required to create an invite");
      return;
    }
    try {
      const data = await client.request(`/rooms/${activeRoom}/invite`, {
        method: "POST",
        body: JSON.stringify({ email: inviteEmail }),
      });
      setInviteToken(data.invite_token);
      setMsg("Invite token generated – share it with the other reader");
    } catch (e) {
      setMsg(e.message);
    }
  }

  // Accept an invitation token received from another user.
  async function acceptInvite() {
    if (!inviteTokenInput) {
      setMsg("Invite token is required");
      return;
    }
    try {
      const resp = await client.request(`/api/rooms/invite/accept`, {
        method: "POST",
        body: JSON.stringify({ token: inviteTokenInput }),
      });
      // The server returns the room_id; we can set it as active.
      setActiveRoom(resp.room_id);
      setInviteTokenInput("");
      setMsg("Joined room via invite token");
    } catch (e) {
      setMsg(e.message);
    }
  }

  const bookRooms = rooms.filter(
    (r) => r.book_id === book.id || r.title === book.title,
  );
  const currentPage = pages[pageIndex] || "";
  const totalPages = pages.length;

  return (
    <div style={{}}>
      <div className="reader-shell monochrome">
        <button
          onClick={() => setShowChapters(true)}
          style={{
            position: "fixed",
            top: 20,
            left: 20,
            zIndex: 1000,
            padding: "10px 18px",
            borderRadius: "8px",
            border: "1px solid #ddd",
            background: "#fff",
            cursor: "pointer",
            fontWeight: 600,
          }}
        >
          ☰ Chapters
        </button>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            flex: "1",
            maxHeight: "calc(100vh - 80px)",
            marginTop: "5px",
          }}
        >
          <button
            className="nav-btn prev-btn"
            disabled={pageIndex === 0}
            onClick={() => setPageIndex((p) => p - 1)}
            aria-label="Previous page"
          >
            <ChevronLeft size={24} />
          </button>
          <div
            // className="reader-container"
            style={{
              width: "100%",
              maxWidth: "900px",
              margin: "0 auto",
            }}
          >
            {/* Main reading area */}
            <div
              className="book-page-content"
              style={{
                width: "100%",
                maxWidth: "900px",
                height: "calc(100vh - 90px)", // fills the viewport
                margin: "0 auto",
                padding: "40px 55px",
                background: "#fff",
                display: "flex",
                flexDirection: "column",
                overflow: "hidden", // prevents scrolling
                boxSizing: "border-box",
              }}
            >
              {/* Book page */}

              <div>
                <div>
                  <div />
                  <div ref={textRef}>
                    <div />
                    <p
                      style={{
                        whiteSpace: "pre-wrap",
                        lineHeight: "2",
                        fontSize: "20px",
                        maxWidth: "800px",
                        margin: "0 auto",
                        color: "#222",
                        textAlign: "justify",
                        fontFamily: "Georgia, serif",
                      }}
                    >
                      {currentPage}
                    </p>
                    <div />
                    <div>
                      <span>{book.author}</span>
                      <span>{book.ebook_source}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Side panel – notes, bookmarks, or room management */}

              {showPanel && (
                <aside>
                  <div>
                    <h3>
                      {showPanel === "room" && "Reading rooms"}
                      {showPanel === "notes" && "Notes"}
                      {showPanel === "bookmarks" && "Bookmarks"}
                    </h3>
                    <button onClick={() => setShowPanel(null)}>
                      <X size={16} />
                    </button>
                  </div>

                  {msg && <p>{msg}</p>}

                  {/* Room creation / management */}
                  {showPanel === "room" && (
                    <div>
                      {/* If not yet joined, show join/create UI */}
                      {!activeRoom ? (
                        <>
                          <p>
                            Join or start a room to take notes and add bookmarks
                            with others.
                          </p>
                          <button onClick={createRoom}>
                            + Start room for this book
                          </button>
                          {bookRooms.length > 0 && (
                            <>
                              <p>Existing rooms</p>
                              {bookRooms.map((r) => (
                                <button
                                  key={r.id}
                                  onClick={() => joinRoom(r.id)}
                                >
                                  <span>{r.name}</span>
                                  <span>{r.member_count} readers</span>
                                </button>
                              ))}
                            </>
                          )}
                        </>
                      ) : (
                        <div>
                          {/* Inside a joined room – show members, notes, invites */}
                          <div>
                            <Users size={14} />
                            {roomData && roomData.members
                              ? roomData.members.map((m) => m.name).join(", ")
                              : "Loading..."}
                          </div>
                          <p>You are in a collaborative reading room.</p>
                          {/* Invite creation UI */}
                          <div style={{ marginTop: "12px" }}>
                            <input
                              placeholder="Invitee email"
                              value={inviteEmail}
                              onChange={(e) => setInviteEmail(e.target.value)}
                              style={{ marginRight: "8px" }}
                            />
                            <button onClick={createInvite}>
                              Create Invite
                            </button>
                            {inviteToken && (
                              <div
                                style={{
                                  marginTop: "8px",
                                  wordBreak: "break-all",
                                }}
                              >
                                <strong>Invite token:</strong> {inviteToken}
                              </div>
                            )}
                          </div>
                          <button
                            onClick={() => {
                              setActiveRoom(null);
                              setRoomData(null);
                            }}
                          >
                            Leave room
                          </button>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Notes UI */}
                  {showPanel === "notes" && activeRoom && (
                    <div>
                      <form onSubmit={addNote}>
                        <p>New note — Page {pageIndex + 1}</p>
                        <textarea
                          rows="3"
                          placeholder="Write a note about this page..."
                          value={noteBody}
                          onChange={(e) => setNoteBody(e.target.value)}
                        />
                        <button>
                          <NotebookPen size={14} /> Save note
                        </button>
                      </form>
                      <p>All notes</p>
                      {roomData?.notes?.length === 0 && <p>No notes yet.</p>}
                      {roomData?.notes?.map((n) => (
                        <div key={n.id}>
                          <span>{n.location}</span>
                          <p>{n.body}</p>
                          <span>— {n.user_name}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Bookmarks UI */}
                  {showPanel === "bookmarks" && activeRoom && (
                    <div>
                      <form onSubmit={addBookmark}>
                        <p>Bookmark page {pageIndex + 1}</p>
                        <input
                          placeholder="Label for this bookmark"
                          value={bookmarkLabel}
                          onChange={(e) => setBookmarkLabel(e.target.value)}
                        />
                        <button>
                          <Bookmark size={14} /> Add bookmark
                        </button>
                      </form>
                      <p>All bookmarks</p>
                      {roomData?.bookmarks?.length === 0 && (
                        <p>No bookmarks yet.</p>
                      )}
                      {roomData?.bookmarks?.map((b) => (
                        <div key={b.id}>
                          <span>{b.location}</span>
                          <p>{b.label}</p>
                          <span>— {b.user_name}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </aside>
              )}
              {chapters.length > 0 && (
                <aside className="chapter-index absolute top-0 right-0 h-full w-48 overflow-y-auto bg-white shadow-lg p-2 z-10">
                  <h3 className="font-medium mb-2">Chapters</h3>
                  <ul className="space-y-1">
                    {chapters.map((c, i) => (
                      <li key={i}>
                        <button
                          className={`text-left w-full text-sm ${pageIndex === c.pageIndex ? "font-bold" : ""}`}
                          onClick={() => setPageIndex(c.pageIndex)}
                        >
                          {c.title}
                        </button>
                      </li>
                    ))}
                  </ul>
                </aside>
              )}
            </div>
          </div>

          <button
            className="nav-btn next-btn"
            disabled={pageIndex >= totalPages - 1}
            onClick={() => setPageIndex((p) => p + 1)}
            aria-label="Next page"
          >
            <ChevronRight size={24} />
          </button>
        </div>
        <footer className="page-footer">
          Page {pageIndex + 1} of {totalPages}
        </footer>
        {showChapters && (
          <>
            <div
              onClick={() => setShowChapters(false)}
              style={{
                position: "fixed",
                inset: 0,
                background: "rgba(0,0,0,.35)",
                zIndex: 99,
              }}
            />

            <aside
              style={{
                position: "fixed",
                left: 0,
                top: 0,
                width: "320px",
                height: "100vh",
                background: "#fff",
                zIndex: 100,
                overflowY: "auto",
                borderRight: "1px solid #ddd",
                boxShadow: "2px 0 20px rgba(0,0,0,.15)",
              }}
            >

              {chapters.map((chapter, i) => (
                <button
                  key={i}
                  onClick={() => {
                    setPageIndex(chapter.pageIndex);
                    setShowChapters(false);
                  }}
                  style={{
                    color:"black",
                    width: "100%",
                    padding: "16px 20px",
                    textAlign: "left",
                    border: "none",
                    background:
                      pageIndex === chapter.pageIndex ? "#f3f3f3" : "#fff",
                    borderBottom: "1px solid #eee",
                    cursor: "pointer",
                  }}
                >
                  <div style={{ fontWeight: 600 }}>{chapter.title}</div>

                  <div
                    style={{
                      fontSize: 12,
                      color: "#777",
                      marginTop: 4,
                    }}
                  >
                    Page {chapter.pageIndex + 1}
                  </div>
                </button>
              ))}
            </aside>
          </>
        )}
      </div>
    </div>
  );
}
